/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DurationSeconds = bigint;
export interface MeetingHistoryEntry {
  'title' : string,
  'date' : Timestamp,
  'role' : { 'host' : null } |
    { 'participant' : null },
  'durationSeconds' : [] | [DurationSeconds],
  'participantCount' : bigint,
  'roomCode' : RoomCode,
}
export interface ParticipantInfo {
  'screenSharing' : boolean,
  'displayName' : string,
  'userId' : string,
  'joinedAt' : Timestamp,
  'isActive' : boolean,
  'leftAt' : [] | [Timestamp],
  'isMuted' : boolean,
  'roomCode' : RoomCode,
  'cameraOn' : boolean,
}
export interface RecordingInfo {
  'id' : bigint,
  'createdAt' : Timestamp,
  'participantsCount' : bigint,
  'durationSeconds' : DurationSeconds,
  'roomCode' : RoomCode,
  'uploadedBy' : string,
  'fileUrl' : Url,
}
export type RoomCode = string;
export interface RoomInfo {
  'status' : RoomStatus,
  'title' : string,
  'code' : RoomCode,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'closedAt' : [] | [Timestamp],
  'participantCount' : bigint,
}
export type RoomStatus = { 'closed' : null } |
  { 'active' : null };
export interface SignalInfo {
  'id' : bigint,
  'createdAt' : Timestamp,
  'toUser' : string,
  'consumed' : boolean,
  'fromUser' : string,
  'roomCode' : RoomCode,
  'payload' : string,
  'signalType' : SignalType,
}
export type SignalType = { 'ice' : null } |
  { 'offer' : null } |
  { 'answer' : null };
export interface StrokeInfo {
  'id' : bigint,
  'userId' : string,
  'createdAt' : Timestamp,
  'path' : string,
  'color' : string,
  'width' : bigint,
  'roomCode' : RoomCode,
}
export type Timestamp = bigint;
export type Url = string;
export interface _SERVICE {
  'addStroke' : ActorMethod<[RoomCode, string, bigint, string], bigint>,
  'clearWhiteboard' : ActorMethod<[RoomCode], undefined>,
  'closeRoom' : ActorMethod<[RoomCode], boolean>,
  'consumeSignals' : ActorMethod<[Array<bigint>], bigint>,
  'createRoom' : ActorMethod<[string], RoomCode>,
  'getPendingSignals' : ActorMethod<[RoomCode], Array<SignalInfo>>,
  'getRecordingById' : ActorMethod<[bigint], [] | [RecordingInfo]>,
  'getRoomInfo' : ActorMethod<[RoomCode], [] | [RoomInfo]>,
  'getStrokes' : ActorMethod<[RoomCode], Array<StrokeInfo>>,
  'joinRoom' : ActorMethod<[RoomCode, string], boolean>,
  'leaveRoom' : ActorMethod<[RoomCode], boolean>,
  'listMeetingHistory' : ActorMethod<[], Array<MeetingHistoryEntry>>,
  'listMyRecordings' : ActorMethod<[], Array<RecordingInfo>>,
  'listParticipants' : ActorMethod<[RoomCode], Array<ParticipantInfo>>,
  'saveRecording' : ActorMethod<
    [RoomCode, DurationSeconds, Url, bigint],
    bigint
  >,
  'sendAnswer' : ActorMethod<[Principal, RoomCode, string], bigint>,
  'sendIce' : ActorMethod<[Principal, RoomCode, string], bigint>,
  'sendOffer' : ActorMethod<[Principal, RoomCode, string], bigint>,
  'updateMyState' : ActorMethod<
    [RoomCode, [] | [boolean], [] | [boolean], [] | [boolean]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];