/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomCode = IDL.Text;
export const Timestamp = IDL.Int;
export const SignalType = IDL.Variant({
  'ice' : IDL.Null,
  'offer' : IDL.Null,
  'answer' : IDL.Null,
});
export const SignalInfo = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'toUser' : IDL.Text,
  'consumed' : IDL.Bool,
  'fromUser' : IDL.Text,
  'roomCode' : RoomCode,
  'payload' : IDL.Text,
  'signalType' : SignalType,
});
export const DurationSeconds = IDL.Nat;
export const Url = IDL.Text;
export const RecordingInfo = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'participantsCount' : IDL.Nat,
  'durationSeconds' : DurationSeconds,
  'roomCode' : RoomCode,
  'uploadedBy' : IDL.Text,
  'fileUrl' : Url,
});
export const RoomStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
});
export const RoomInfo = IDL.Record({
  'status' : RoomStatus,
  'title' : IDL.Text,
  'code' : RoomCode,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'closedAt' : IDL.Opt(Timestamp),
  'participantCount' : IDL.Nat,
});
export const StrokeInfo = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Text,
  'createdAt' : Timestamp,
  'path' : IDL.Text,
  'color' : IDL.Text,
  'width' : IDL.Nat,
  'roomCode' : RoomCode,
});
export const MeetingHistoryEntry = IDL.Record({
  'title' : IDL.Text,
  'date' : Timestamp,
  'role' : IDL.Variant({ 'host' : IDL.Null, 'participant' : IDL.Null }),
  'durationSeconds' : IDL.Opt(DurationSeconds),
  'participantCount' : IDL.Nat,
  'roomCode' : RoomCode,
});
export const ParticipantInfo = IDL.Record({
  'screenSharing' : IDL.Bool,
  'displayName' : IDL.Text,
  'userId' : IDL.Text,
  'joinedAt' : Timestamp,
  'isActive' : IDL.Bool,
  'leftAt' : IDL.Opt(Timestamp),
  'isMuted' : IDL.Bool,
  'roomCode' : RoomCode,
  'cameraOn' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addStroke' : IDL.Func(
      [RoomCode, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'clearWhiteboard' : IDL.Func([RoomCode], [], []),
  'closeRoom' : IDL.Func([RoomCode], [IDL.Bool], []),
  'consumeSignals' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'createRoom' : IDL.Func([IDL.Text], [RoomCode], []),
  'getPendingSignals' : IDL.Func([RoomCode], [IDL.Vec(SignalInfo)], []),
  'getRecordingById' : IDL.Func([IDL.Nat], [IDL.Opt(RecordingInfo)], ['query']),
  'getRoomInfo' : IDL.Func([RoomCode], [IDL.Opt(RoomInfo)], ['query']),
  'getStrokes' : IDL.Func([RoomCode], [IDL.Vec(StrokeInfo)], ['query']),
  'joinRoom' : IDL.Func([RoomCode, IDL.Text], [IDL.Bool], []),
  'leaveRoom' : IDL.Func([RoomCode], [IDL.Bool], []),
  'listMeetingHistory' : IDL.Func([], [IDL.Vec(MeetingHistoryEntry)], []),
  'listMyRecordings' : IDL.Func([], [IDL.Vec(RecordingInfo)], []),
  'listParticipants' : IDL.Func(
      [RoomCode],
      [IDL.Vec(ParticipantInfo)],
      ['query'],
    ),
  'saveRecording' : IDL.Func(
      [RoomCode, DurationSeconds, Url, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'sendAnswer' : IDL.Func([IDL.Principal, RoomCode, IDL.Text], [IDL.Nat], []),
  'sendIce' : IDL.Func([IDL.Principal, RoomCode, IDL.Text], [IDL.Nat], []),
  'sendOffer' : IDL.Func([IDL.Principal, RoomCode, IDL.Text], [IDL.Nat], []),
  'updateMyState' : IDL.Func(
      [RoomCode, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomCode = IDL.Text;
  const Timestamp = IDL.Int;
  const SignalType = IDL.Variant({
    'ice' : IDL.Null,
    'offer' : IDL.Null,
    'answer' : IDL.Null,
  });
  const SignalInfo = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'toUser' : IDL.Text,
    'consumed' : IDL.Bool,
    'fromUser' : IDL.Text,
    'roomCode' : RoomCode,
    'payload' : IDL.Text,
    'signalType' : SignalType,
  });
  const DurationSeconds = IDL.Nat;
  const Url = IDL.Text;
  const RecordingInfo = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'participantsCount' : IDL.Nat,
    'durationSeconds' : DurationSeconds,
    'roomCode' : RoomCode,
    'uploadedBy' : IDL.Text,
    'fileUrl' : Url,
  });
  const RoomStatus = IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null });
  const RoomInfo = IDL.Record({
    'status' : RoomStatus,
    'title' : IDL.Text,
    'code' : RoomCode,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'closedAt' : IDL.Opt(Timestamp),
    'participantCount' : IDL.Nat,
  });
  const StrokeInfo = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Text,
    'createdAt' : Timestamp,
    'path' : IDL.Text,
    'color' : IDL.Text,
    'width' : IDL.Nat,
    'roomCode' : RoomCode,
  });
  const MeetingHistoryEntry = IDL.Record({
    'title' : IDL.Text,
    'date' : Timestamp,
    'role' : IDL.Variant({ 'host' : IDL.Null, 'participant' : IDL.Null }),
    'durationSeconds' : IDL.Opt(DurationSeconds),
    'participantCount' : IDL.Nat,
    'roomCode' : RoomCode,
  });
  const ParticipantInfo = IDL.Record({
    'screenSharing' : IDL.Bool,
    'displayName' : IDL.Text,
    'userId' : IDL.Text,
    'joinedAt' : Timestamp,
    'isActive' : IDL.Bool,
    'leftAt' : IDL.Opt(Timestamp),
    'isMuted' : IDL.Bool,
    'roomCode' : RoomCode,
    'cameraOn' : IDL.Bool,
  });
  
  return IDL.Service({
    'addStroke' : IDL.Func(
        [RoomCode, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'clearWhiteboard' : IDL.Func([RoomCode], [], []),
    'closeRoom' : IDL.Func([RoomCode], [IDL.Bool], []),
    'consumeSignals' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'createRoom' : IDL.Func([IDL.Text], [RoomCode], []),
    'getPendingSignals' : IDL.Func([RoomCode], [IDL.Vec(SignalInfo)], []),
    'getRecordingById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RecordingInfo)],
        ['query'],
      ),
    'getRoomInfo' : IDL.Func([RoomCode], [IDL.Opt(RoomInfo)], ['query']),
    'getStrokes' : IDL.Func([RoomCode], [IDL.Vec(StrokeInfo)], ['query']),
    'joinRoom' : IDL.Func([RoomCode, IDL.Text], [IDL.Bool], []),
    'leaveRoom' : IDL.Func([RoomCode], [IDL.Bool], []),
    'listMeetingHistory' : IDL.Func([], [IDL.Vec(MeetingHistoryEntry)], []),
    'listMyRecordings' : IDL.Func([], [IDL.Vec(RecordingInfo)], []),
    'listParticipants' : IDL.Func(
        [RoomCode],
        [IDL.Vec(ParticipantInfo)],
        ['query'],
      ),
    'saveRecording' : IDL.Func(
        [RoomCode, DurationSeconds, Url, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'sendAnswer' : IDL.Func([IDL.Principal, RoomCode, IDL.Text], [IDL.Nat], []),
    'sendIce' : IDL.Func([IDL.Principal, RoomCode, IDL.Text], [IDL.Nat], []),
    'sendOffer' : IDL.Func([IDL.Principal, RoomCode, IDL.Text], [IDL.Nat], []),
    'updateMyState' : IDL.Func(
        [RoomCode, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };