/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SignalInfo {
    id: bigint;
    createdAt: Timestamp;
    toUser: string;
    consumed: boolean;
    fromUser: string;
    roomCode: RoomCode;
    payload: string;
    signalType: SignalType;
}
export interface RecordingInfo {
    id: bigint;
    createdAt: Timestamp;
    participantsCount: bigint;
    durationSeconds: DurationSeconds;
    roomCode: RoomCode;
    uploadedBy: string;
    fileUrl: Url;
}
export type Timestamp = bigint;
export interface MeetingHistoryEntry {
    title: string;
    date: Timestamp;
    role: Variant_host_participant;
    durationSeconds?: DurationSeconds;
    participantCount: bigint;
    roomCode: RoomCode;
}
export type RoomCode = string;
export interface StrokeInfo {
    id: bigint;
    userId: string;
    createdAt: Timestamp;
    path: string;
    color: string;
    width: bigint;
    roomCode: RoomCode;
}
export interface ParticipantInfo {
    screenSharing: boolean;
    displayName: string;
    userId: string;
    joinedAt: Timestamp;
    isActive: boolean;
    leftAt?: Timestamp;
    isMuted: boolean;
    roomCode: RoomCode;
    cameraOn: boolean;
}
export type DurationSeconds = bigint;
export interface RoomInfo {
    status: RoomStatus;
    title: string;
    code: RoomCode;
    createdAt: Timestamp;
    createdBy: string;
    closedAt?: Timestamp;
    participantCount: bigint;
}
export type Url = string;
export enum RoomStatus {
    closed = "closed",
    active = "active"
}
export enum SignalType {
    ice = "ice",
    offer = "offer",
    answer = "answer"
}
export enum Variant_host_participant {
    host = "host",
    participant = "participant"
}
export interface backendInterface {
    addStroke(roomCode: RoomCode, color: string, width: bigint, path: string): Promise<bigint>;
    clearWhiteboard(roomCode: RoomCode): Promise<void>;
    closeRoom(code: RoomCode): Promise<boolean>;
    consumeSignals(ids: Array<bigint>): Promise<bigint>;
    createRoom(title: string): Promise<RoomCode>;
    getPendingSignals(roomCode: RoomCode): Promise<Array<SignalInfo>>;
    getRecordingById(id: bigint): Promise<RecordingInfo | null>;
    getRoomInfo(code: RoomCode): Promise<RoomInfo | null>;
    getStrokes(roomCode: RoomCode): Promise<Array<StrokeInfo>>;
    joinRoom(roomCode: RoomCode, displayName: string): Promise<boolean>;
    leaveRoom(roomCode: RoomCode): Promise<boolean>;
    listMeetingHistory(): Promise<Array<MeetingHistoryEntry>>;
    listMyRecordings(): Promise<Array<RecordingInfo>>;
    listParticipants(roomCode: RoomCode): Promise<Array<ParticipantInfo>>;
    saveRecording(roomCode: RoomCode, durationSeconds: DurationSeconds, fileUrl: Url, participantsCount: bigint): Promise<bigint>;
    sendAnswer(toUser: Principal, roomCode: RoomCode, payload: string): Promise<bigint>;
    sendIce(toUser: Principal, roomCode: RoomCode, payload: string): Promise<bigint>;
    sendOffer(toUser: Principal, roomCode: RoomCode, payload: string): Promise<bigint>;
    updateMyState(roomCode: RoomCode, isMuted: boolean | null, cameraOn: boolean | null, screenSharing: boolean | null): Promise<boolean>;
}
import type { DurationSeconds as _DurationSeconds, MeetingHistoryEntry as _MeetingHistoryEntry, ParticipantInfo as _ParticipantInfo, RecordingInfo as _RecordingInfo, RoomCode as _RoomCode, RoomInfo as _RoomInfo, RoomStatus as _RoomStatus, SignalInfo as _SignalInfo, SignalType as _SignalType, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addStroke(arg0: RoomCode, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStroke(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStroke(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async clearWhiteboard(arg0: RoomCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearWhiteboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearWhiteboard(arg0);
            return result;
        }
    }
    async closeRoom(arg0: RoomCode): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.closeRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeRoom(arg0);
            return result;
        }
    }
    async consumeSignals(arg0: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.consumeSignals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consumeSignals(arg0);
            return result;
        }
    }
    async createRoom(arg0: string): Promise<RoomCode> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0);
            return result;
        }
    }
    async getPendingSignals(arg0: RoomCode): Promise<Array<SignalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSignals(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSignals(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecordingById(arg0: bigint): Promise<RecordingInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordingById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordingById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomInfo(arg0: RoomCode): Promise<RoomInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomInfo(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomInfo(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrokes(arg0: RoomCode): Promise<Array<StrokeInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrokes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrokes(arg0);
            return result;
        }
    }
    async joinRoom(arg0: RoomCode, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1);
            return result;
        }
    }
    async leaveRoom(arg0: RoomCode): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRoom(arg0);
            return result;
        }
    }
    async listMeetingHistory(): Promise<Array<MeetingHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMeetingHistory();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMeetingHistory();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyRecordings(): Promise<Array<RecordingInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyRecordings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyRecordings();
            return result;
        }
    }
    async listParticipants(arg0: RoomCode): Promise<Array<ParticipantInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listParticipants(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listParticipants(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveRecording(arg0: RoomCode, arg1: DurationSeconds, arg2: Url, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRecording(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRecording(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendAnswer(arg0: Principal, arg1: RoomCode, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAnswer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAnswer(arg0, arg1, arg2);
            return result;
        }
    }
    async sendIce(arg0: Principal, arg1: RoomCode, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendIce(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendIce(arg0, arg1, arg2);
            return result;
        }
    }
    async sendOffer(arg0: Principal, arg1: RoomCode, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendOffer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendOffer(arg0, arg1, arg2);
            return result;
        }
    }
    async updateMyState(arg0: RoomCode, arg1: boolean | null, arg2: boolean | null, arg3: boolean | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyState(arg0, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyState(arg0, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_MeetingHistoryEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MeetingHistoryEntry): MeetingHistoryEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ParticipantInfo_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParticipantInfo): ParticipantInfo {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RoomInfo_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomInfo): RoomInfo {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RoomStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomStatus): RoomStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SignalInfo_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalInfo): SignalInfo {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SignalType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalType): SignalType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DurationSeconds]): DurationSeconds | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecordingInfo]): RecordingInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomInfo]): RoomInfo | null {
    return value.length === 0 ? null : from_candid_RoomInfo_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: _Timestamp;
    role: {
        host: null;
    } | {
        participant: null;
    };
    durationSeconds: [] | [_DurationSeconds];
    participantCount: bigint;
    roomCode: _RoomCode;
}): {
    title: string;
    date: Timestamp;
    role: Variant_host_participant;
    durationSeconds?: DurationSeconds;
    participantCount: bigint;
    roomCode: RoomCode;
} {
    return {
        title: value.title,
        date: value.date,
        role: from_candid_variant_n16(_uploadFile, _downloadFile, value.role),
        durationSeconds: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.durationSeconds)),
        participantCount: value.participantCount,
        roomCode: value.roomCode
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    screenSharing: boolean;
    displayName: string;
    userId: string;
    joinedAt: _Timestamp;
    isActive: boolean;
    leftAt: [] | [_Timestamp];
    isMuted: boolean;
    roomCode: _RoomCode;
    cameraOn: boolean;
}): {
    screenSharing: boolean;
    displayName: string;
    userId: string;
    joinedAt: Timestamp;
    isActive: boolean;
    leftAt?: Timestamp;
    isMuted: boolean;
    roomCode: RoomCode;
    cameraOn: boolean;
} {
    return {
        screenSharing: value.screenSharing,
        displayName: value.displayName,
        userId: value.userId,
        joinedAt: value.joinedAt,
        isActive: value.isActive,
        leftAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.leftAt)),
        isMuted: value.isMuted,
        roomCode: value.roomCode,
        cameraOn: value.cameraOn
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: _Timestamp;
    toUser: string;
    consumed: boolean;
    fromUser: string;
    roomCode: _RoomCode;
    payload: string;
    signalType: _SignalType;
}): {
    id: bigint;
    createdAt: Timestamp;
    toUser: string;
    consumed: boolean;
    fromUser: string;
    roomCode: RoomCode;
    payload: string;
    signalType: SignalType;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        toUser: value.toUser,
        consumed: value.consumed,
        fromUser: value.fromUser,
        roomCode: value.roomCode,
        payload: value.payload,
        signalType: from_candid_SignalType_n4(_uploadFile, _downloadFile, value.signalType)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RoomStatus;
    title: string;
    code: _RoomCode;
    createdAt: _Timestamp;
    createdBy: string;
    closedAt: [] | [_Timestamp];
    participantCount: bigint;
}): {
    status: RoomStatus;
    title: string;
    code: RoomCode;
    createdAt: Timestamp;
    createdBy: string;
    closedAt?: Timestamp;
    participantCount: bigint;
} {
    return {
        status: from_candid_RoomStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        code: value.code,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        closedAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.closedAt)),
        participantCount: value.participantCount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
}): RoomStatus {
    return "closed" in value ? RoomStatus.closed : "active" in value ? RoomStatus.active : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    host: null;
} | {
    participant: null;
}): Variant_host_participant {
    return "host" in value ? Variant_host_participant.host : "participant" in value ? Variant_host_participant.participant : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ice: null;
} | {
    offer: null;
} | {
    answer: null;
}): SignalType {
    return "ice" in value ? SignalType.ice : "offer" in value ? SignalType.offer : "answer" in value ? SignalType.answer : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignalInfo>): Array<SignalInfo> {
    return value.map((x)=>from_candid_SignalInfo_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MeetingHistoryEntry>): Array<MeetingHistoryEntry> {
    return value.map((x)=>from_candid_MeetingHistoryEntry_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ParticipantInfo>): Array<ParticipantInfo> {
    return value.map((x)=>from_candid_ParticipantInfo_n19(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
